import newsSeed from "../../public/api/news.json";
import type { NewsStory } from "@/types/news";

/**
 * Build-time snapshot of recent published news stories. The live feed is read
 * from Supabase at runtime (see useNews); this seed gives the server-rendered
 * page instant first paint, sr-only SEO content, and JSON-LD. Regenerated by
 * scripts/generate-news-seed.js in the prebuild step.
 */
export function getNewsSeed(): NewsStory[] {
  return newsSeed as NewsStory[];
}
